# Simple CI for AI Solutions Lab
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        
    - name: Run tests
      run: |
        python -m pytest tests/ -v
        
    - name: Test RAG demo
      run: |
        python src/ai_lab/simple_rag.py
        
    - name: Test FastAPI app loads
      run: |
        python -c "from src.ai_lab.app import app; print('✅ FastAPI app loads successfully')"
