# Optimized CI for AI Solutions Lab
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
        test-group: ['fast', 'full']
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # Enable pip caching
        
    - name: Install minimal test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
        
    - name: Install ML dependencies (only for full test group)
      if: matrix.test-group == 'full'
      run: |
        pip install sentence-transformers faiss-cpu
        
    - name: Run fast tests
      if: matrix.test-group == 'fast'
      run: |
        python -m pytest tests/test_simple.py tests/test_task_b.py -v
        
    - name: Run full tests
      if: matrix.test-group == 'full'
      run: |
        python -m pytest tests/ -v
        
    - name: Test RAG demo
      run: |
        python src/ai_lab/simple_rag.py
        
    - name: Test FastAPI app loads
      run: |
        python -c "from src.ai_lab.app import app; print('✅ FastAPI app loads successfully')"
