# Optimized CI for AI Solutions Lab
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
        test-group: ['fast', 'full']
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # Enable pip caching
        
    - name: Install fast test dependencies
      if: matrix.test-group == 'fast'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-fast.txt
        
    - name: Install full test dependencies
      if: matrix.test-group == 'full'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
        
    - name: Run fast tests
      if: matrix.test-group == 'fast'
      run: |
        python -m pytest tests/test_fast.py -v
        
    - name: Run full tests
      if: matrix.test-group == 'full'
      run: |
        python -m pytest tests/test_simple.py tests/test_task_b.py tests/test_task_f_simple.py -v
        
    - name: Test basic functionality (full tests only)
      if: matrix.test-group == 'full'
      run: |
        python -c "from src.ai_lab.app import app; print('✅ FastAPI app loads successfully')"
